### ISSUE TITLE
iOS 11 NSInvalidArgumentException crash

### ISSUE THREAD

**Issue by lubieapki** [JRock007/Tob#9]
The app crashes immediately upon opening. It shows the screen with the logo for one second and then disappears. iPhone 7+

**Comment by lubieapki** [comment]
Are you?

**Comment by JRock007** [comment]
I don't have access to a physical copy of an iPhone 7+ and I haven't been able to reproduce this issue in the simulator. I'm guessing you're using a physical copy.
If you add a breakpoint for all exceptions, is it triggered? Have you changed anything in the app?

**Comment by lubieapki** [comment]
@JRock007  I've already dealt with it was iOS 11 fault, I back to iOS 10 and it works

But now I have a problem. Look at the screenshot
![img_2425 png](https://user-images.githubusercontent.com/6787484/29748727-23006122-8b1c-11e7-94f9-651055d5923c.png)

**Comment by JRock007** [comment]
@lubieapki I'll look into the iOS 11 issue then, thanks for reporting that.
Right now, the IP is detected by making a request to duckduckgo which sometimes fails. I've started implementing a better way, to get the whole circuit, in 622c3e957a86d09ee0638e5f1e1e936b959e542c but there still are some issues I have to fix.

**Comment by JRock007** [comment]
The crash on iOS 11 doesn't occur on the iPhone SE for some reason, but it does on other devices.
It only crashes on the first launch of the app when trying to initialise Bookmarks:
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+entityForName: nil is not a legal NSPersistentStoreCoordinator for searching for entity name 'Bookmark''`

The issue seems to be that `[appDelegate managedObjectContext]` returns nil. Apparently it's a common problem for people using Apple's code, so I'll probably change the code like [this](http://commandshift.co.uk/blog/2013/09/07/the-core-data-stack/).
